spring.application.name: apiclient
server.port: 8080
spring.main.banner-mode: off

## ログレベル
logging.level:
  com.example: DEBUG

## thymeleaf
spring.thymeleaf.mode: HTML

## Spring Security (OAuth2クライアント)
spring.security.oauth2.client.registration:
  demoapp:
    provider: keycloak
    client-id: demoapp
    client-secret: 08c33835-c18c-4dd7-a7df-aee3479d17c4
    scope: openid
spring.security.oauth2.client.provider:
  keycloak:
    issuer-uri: http://localhost:18080/auth/realms/demo

services:
  hello:
    base-url: http://localhost:8081/api/v1/
    client-registration-id: demoapp
