spring.application.name: apiserver
server.port: 8081
spring.webflux.base-path: /api/v1
spring.main.banner-mode: off

## ログレベル
logging.level:
  com.example: DEBUG

my.urls:
  back-auth: http://localhost:18080/auth

## Spring Security (リソースサーバー)
spring.security.oauth2.resourceserver:
  jwt:
    jwk-set-uri: ${my.urls.back-auth}/realms/demo/protocol/openid-connect/certs
    # jws-algorithm: RS256
    # issuer-uri: ${my.urls.back-auth}/realms/demo
