spring.application.name: apiserver
server.port: 8081
spring.webflux.base-path: /api/v1
spring.main.banner-mode: off

## ログレベル
logging.level:
  com.example: DEBUG

## Spring Security (リソースサーバー)
spring.security.oauth2.resourceserver:
  jwt:
    issuer-uri: http://localhost:18080/auth/realms/demo
