spring.main.banner-mode: off

## ログレベル
logging.level:
  example: DEBUG

my:
  issuer-uri: http://localhost:18080/auth/realms/demo
  client_id: demoapp
  client_secret: 08c33835-c18c-4dd7-a7df-aee3479d17c4
  access_token: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIwVFdVYkxmcGxYVXZRTGctTVRPYjBtZ0JzRll6QnNnMm4yR09ONTJMek9BIn0.eyJleHAiOjE2MjAwNTk3NTMsImlhdCI6MTYyMDA1OTQ1MywiYXV0aF90aW1lIjoxNjIwMDU5NDUzLCJqdGkiOiI3NWQ4YWZlOS05MjMwLTRhOWMtYTllYS05ODYxNTBhYmYyYzYiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjE4MDgwL2F1dGgvcmVhbG1zL2RlbW8iLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiM2E4NjViNGUtMTE2OS00NDlkLWJkZWUtNmEwOGE2YzMxY2ExIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiZGVtb2FwcCIsInNlc3Npb25fc3RhdGUiOiIzZGI4OTU3Mi01ZGQzLTQ5N2EtOGFkZS05NmNhY2YzYzNiM2QiLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyMSJ9.mUOGbls65-8z3Jq7UCuPECQwfhYdPWA1CzC6meU4K0BsRiBxhh90f1wzCmzpV4XWME71Fw0IXhDBfGrGvJhGNhB2W43u60mRhohmQc2eheBlEh6potSNSGorF5bKnzTwX4H-0KUkJLCicb2SYYcq5z3YEwAgNwX0_HrH11LTjuZnOpVT0Jgky8I-qDGnQGUlISyhfpcba1L7icxX6fvvU-a26SS7OtFkF3VvAZyynjnJeuoGF60EWCbXsnv1gxyWghnP3dM-cJntQo5eJnfYLXIFTkYZzsBA2smA1c4mkNsUEH_W0uMwBMDmmn-61YB9qYsChzMfAkAHbjl5gCOk1A
